### ISSUE TITLE
syntax highlighting breaks after setting an int as default value

### ISSUE THREAD

**Issue by rj1** [jidn/vim-dbml#2]
hi there, thanks for this plugin, it rocks! 

I am having an issue w/ the syntax highlighting when setting an int as the default value for a column.

screenshots:

syntax highlighting working without default value set:
![2021-05-18_02-03](https://user-images.githubusercontent.com/83531587/118606576-3735cd80-b77d-11eb-923a-91c74cfcb836.png)

syntax highlighting broken after setting a default value:
![2021-05-18_02-02](https://user-images.githubusercontent.com/83531587/118606518-22f1d080-b77d-11eb-929b-91b93808e286.png)

**Comment by jidn** [comment]
I'll get right on that.  Thanks
