### ISSUE TITLE
Upstreaming this plugin

### ISSUE THREAD

**Issue by jvoisin** [jidn/vim-dbml#4]
Do you have any plans to upstream this plugin into vim?

**Comment by jidn** [comment]
No. I did submit it to polyglot but it was rejected due to small user base.

**Comment by jvoisin** [comment]
Vim supports weird languages, I think it's worth a shot. I can try to do it if you don't want to invest time in this :)

**Comment by jidn** [comment]
I don't know the process, so thank you in advance.
